Hibernate Reactive Guide (non micronaut-data)
micronaut-projects/micronaut-guides pull request #1001
Opened 2022-07-05 16:10 UTC by timyates

Build with ./gradlew micronautHibernateReactiveBuild

Then check build/dist/micronaut-hibernate-reactive-gradle-java.html for the instructions
for adding dependencies and testing.

This PR is prior to me adding a feature, so I want to check it's right before I go further

2022-07-05 16:10 UTC, timyates commented
@dstepanov Hiya! Can you check this is all sensible?  I will eventually make it into a guide, but I want to check it's as you would expect before I work on the feature for https://github.com/micronaut-projects/micronaut-starter/pull/1307#issuecomment-1174951460

2022-07-05 16:16 UTC, sdelamo requested changes

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/Application.java
> +public class Application {
remove this class is auto generated

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/Genre.java
> +@Entity
add callout

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/Genre.java
> +@Table(name = "genre")
add callout

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/Genre.java
> +    @Id
add callout

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/Genre.java
> +    @GeneratedValue(strategy = AUTO)
add callout

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/Genre.java
> +    @Column(name = "name", nullable = false, unique = true)
add callout

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/GenreController.java
> +    Publisher<Genre> save(String name) {
annotate with `@SingleResult` if it returns a single result. or return `Mono`

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/GenreController.java
> +@Controller
add callout

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/GenreController.java
> +    public GenreController(GenreRepository genreRepository) {
add callout

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/GenreController.java
> +    Publisher<Genre> list() {
add callout explaining the ability to return a `Publisher`

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/GenreController.java
> +    @Get
add callout for get

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/GenreRepositoryImpl.java
> +        return Mono.fromCompletionStage(sessionFactory.withTransaction(session -> session.createQuery("from Genre ", Genre.class).getResultList())).flatMapMany(Flux::fromIterable);
break lines so that it is easier to read in a guide

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/resources/logback.xml
> +<configuration>
delete it is generated

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/resources/application.yml
> +jpa:
add asciidoc tag and callouts

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/main/resources/application.yml
> +    name: reactivehibernate
use standard guides name

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/java/src/test/groovy/com/bloidonia/ReactivehibernateSpec.groovy
> +class ReactivehibernateSpec extends Specification {
remove autogenerated test

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/metadata.json
> +      "features": []
we should add the same feature we will add in starter

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/metadata.json
> +  "skipMavenTests": true,
add tests and remove `skipMavenTests` and `skipGradleTests`

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/micronaut-hibernate-reactive.adoc
> +## Run MySql in docker
use common-snippet

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/micronaut-hibernate-reactive.adoc
> +----
use `:dependencies:` macro

2022-07-05 16:16 UTC, sdelamo commented on guides/micronaut-hibernate-reactive/micronaut-hibernate-reactive.adoc
> +[source,bash]
use common snippet to run the app

2022-07-06 07:08 UTC, dstepanov commented on guides/micronaut-hibernate-reactive/java/src/main/java/com/bloidonia/GenreRepository.java
> +    Mono<Genre> create(@NotBlank String name);
Expose all Reactor or all `Publisher` reactive types.

2022-07-06 07:09 UTC, dstepanov commented
Looks fine to me. Maybe I would add some tests.

2022-07-06 11:25 UTC, graemerocher commented
hold on though, this is not using the Micronaut Data implementation on top of Hibernate Reactive? Or is that planned for a separate guide?

2022-07-06 11:27 UTC, sdelamo commented
> hold on though, this is not using the Micronaut Data implementation on top of Hibernate Reactive? Or is that planned for a separate guide?

We will have two guides: 

- Micronaut SQL Hibernate Reactive
- Micronaut Data Hibernate Reactive

2022-07-06 16:09 UTC, timyates commented
## Notes

No Maven yet (see set up instructions for Gradle below)

## SETUP INSTRUCTIONS

### Build the code:

```
./gradlew micronautHibernateReactiveBuild
```

### Open in intellij

```
idea /Users/tim/Code/GitHub/micronaut-projects/micronaut-guides/build/code/micronaut-hibernate-reactive/micronaut-hibernate-reactive-gradle-java
```

### Edit required...

Until we can use a feature for hibernate-reactive, and the micronaut-data release 3.5.0, we need to manually set up some things.

### Add the following to a clean micronaut gradle build:


in repositories
```
   maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
```

in dependencies
```
    implementation("io.micronaut.reactor:micronaut-reactor")
    implementation(platform("io.micronaut.sql:micronaut-sql-bom:4.5.0"))
    implementation("io.micronaut.sql:micronaut-hibernate-reactive")
    implementation("io.vertx:vertx-mysql-client")
    testImplementation("org.testcontainers:testcontainers")
```

somewhere in build.gradle

```
// Pull the snapshot to fix a bug in transaction management under test
configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'io.micronaut.data') {
            details.useVersion "3.5.0-SNAPSHOT"
        }
    }
}
```

Project should compile, and tests should pass

### Run MySql in docker (for running)

```
docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pass mysql:oracle
```

### Run the app

```
./gradlew run
```

### Test the app

```
$ curl http://localhost:8080
[]

$ curl -X POST \
    -d '{"name": "A genre"}' \
    -H "Content-type: application/json" \
    http://localhost:8080
{"id":1,"name":"A genre"}%

$ curl http://localhost:8080
[{"id":1,"name":"A genre"}]%
```

2022-08-04 07:28 UTC, merged