Integration testing
micronaut-projects/micronaut-guides pull request #1009
Opened 2022-07-08 07:13 UTC by mtalaga

I've created simple doc how to integration test micronaut application using bean replacement. This was something I was looking for recently, so founding nothing in the guides I've decided to create one.

There is one thing I've spotted, don't know if it is only my env: the test script is not working. I was trying to break tests and run the script, but everytime it looked like everything passes. Are you aware of that?

2022-07-08 07:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-guides?pullRequest=1009) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-guides?pullRequest=1009) before we can accept your contribution.<br/><hr/>**Michal Talaga** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-guides?pullRequest=1009) it.</sub>

2022-07-08 16:07 UTC, sdelamo requested changes
Thanks for the PR. I have created a couple of suggestions.

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/micronaut-integration-testing.adoc
> +Learn how to provide end-to-end tests with https://guides.micronaut.io/latest/micronaut-rest-assured-gradle-java.html[REST Assured Micronaut Tests].
Please, point people to [Micronaut test](https://micronaut-projects.github.io/micronaut-test/latest/guide/)

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/kotlin/src/test/kotlin/example/micronaut/HelloServiceTest.kt
> +@MicronautTest // <1>
Use `@MicroanutTest(startApplication=false)` You don't need to start the embedded server for the test.

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/micronaut-integration-testing.adoc
> +common:runapp.adoc[]
since your app does not have any controller I will remove the `runapp. adoc` snippet.

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/micronaut-integration-testing.adoc
> +common:graal-with-plugins.adoc[]
since your app does not have any controller I will remove the `common-graal-with-plugins. adoc` snippet.

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/groovy/src/main/groovy/example/micronaut/HelloRepository.groovy
> +    String getHelloInLanguage(String language)
Add Constraints annotations. e.g. `@NotBlank`. I will rename the method to : 
`findHelloByLanguage` which is closer to the naming convention used in Micronaut Data repository.

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/groovy/src/main/groovy/example/micronaut/HelloRepository.groovy
> +    void clearRepository()
delete this method which is only used for tests. add it to the bean replacement.

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/groovy/src/main/groovy/example/micronaut/HelloRepository.groovy
> +    void putHelloInLanguage(String language, String hello)
Add Constraints annotations. e.g. `@NotBlank`. I will rename the method to : 
`save` which is closer to the naming convention used in Micronaut Data repositories.

2022-07-08 16:07 UTC, sdelamo commented on guides/micronaut-integration-testing/groovy/src/main/groovy/example/micronaut/HelloService.groovy
> +    HelloRepository helloRepository
Please, favour constructor injection vs field injection.

2022-07-11 08:12 UTC, mtalaga commented
Thanks for the review, applied all your suggestions.

2022-09-22 17:17 UTC, closed without merging