Object Storage AWS guide
micronaut-projects/micronaut-guides pull request #1086
Opened 2022-09-15 10:39 UTC by alvarosanchez

2022-09-15 15:01 UTC, alvarosanchez commented
PDF version for reviewing:

[Use the Micronaut Object Storage API to store files in AWS S3.pdf](https://github.com/micronaut-projects/micronaut-guides/files/9576429/Use.the.Micronaut.Object.Storage.API.to.store.files.in.AWS.S3.pdf)

2022-09-16 07:23 UTC, sdelamo requested changes
It misses a test and a GraalVM section

I have created a PR with several improvements. I can create multiples PRs instead of a single one if you prefer that. 

https://github.com/micronaut-projects/micronaut-guides/pull/1092

2022-09-16 08:20 UTC, alvarosanchez commented
> It misses a test and a GraalVM section

Regarding the test, if you look at 24ef20d, it had a test with Localstack, but honestly, I thought it would be more confusing, so I removed it. Moreover, for the rest of the clouds, not all the guides can be fully tested with a Testcontainers-based emulator. I tried to use `excludeTest` of `GuideMetadata.App`, but it didn't seem to work.

> I have created a PR with several improvements. I can create multiples PRs instead of a single one if you prefer that.

Thank you very much! It has been merged.

2022-09-16 10:45 UTC, sdelamo commented
> Regarding the test, if you look at [24ef20d](https://github.com/micronaut-projects/micronaut-guides/commit/24ef20d89ef991a08f683ce435368173642c3fad), it had a test with Localstack, but honestly, I thought it would be more confusing, so I removed it. 

We can have a test even if we don't show it in the guide text. I use guide tests as another layer of functional tests.

2022-09-16 13:10 UTC, burtbeckwith requested changes
great guide, significantly better than the one I would have written :)

2022-09-16 13:10 UTC, burtbeckwith commented on guides/micronaut-object-storage-aws/micronaut-object-storage-aws.adoc
> +** An IAM user with enough permissions to create and manage AWS S3 buckets.
remove "enough"

2022-09-16 13:10 UTC, burtbeckwith commented on guides/micronaut-object-storage-aws/micronaut-object-storage-aws.adoc
> +First of all, we are going to
```suggestion
First,
```

2022-09-16 13:10 UTC, burtbeckwith commented on guides/micronaut-object-storage-aws/micronaut-object-storage-aws.adoc
> +For the delete endpoint, all we have to do is invoking the `delete` method with the expected key:
invoking -> invoke

2022-09-16 13:10 UTC, burtbeckwith commented on guides/micronaut-object-storage-aws/micronaut-object-storage-aws.adoc
> +If you want to upload a file bigger than 1MB, you need to configure:
bigger -> larger

2022-09-16 13:32 UTC, burtbeckwith approved these changes

2022-09-18 19:35 UTC, sdelamo requested changes
I have created a PR which addresses the comments in this PR Review. 

https://github.com/micronaut-projects/micronaut-guides/pull/1093

Moreover, I have migrated the test to Java Junit and added the local stack feature so that the test is successfully run in CI.

2022-09-18 19:35 UTC, sdelamo commented on guides/micronaut-object-storage-base/java/src/test/groovy/example/micronaut/AbstractProfilePicturesControllerSpec.groovy
> +        file.text == "micronaut"
this is not testing the contents of the downloaded file.

2022-09-18 19:35 UTC, sdelamo commented on guides/micronaut-object-storage-base/java/src/test/groovy/example/micronaut/AbstractProfilePicturesControllerSpec.groovy
> +        File download = client.toBlocking().retrieve(uri, File.class)
Instead of using `uri`, the location HTTP Header value should be used.

2022-09-18 19:35 UTC, sdelamo commented on guides/micronaut-object-storage-base/java/src/test/groovy/example/micronaut/AbstractProfilePicturesControllerSpec.groovy
> +        File download = client.toBlocking().retrieve(uri, File.class)
I think the correct way to do this is to bind the response to a `byte[]`

2022-09-19 08:51 UTC, sdelamo requested changes

2022-09-19 08:51 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/feature/Localstack.java
> +public class Localstack extends AbstractFeature {
we can delete this right?

2022-09-19 08:52 UTC, sdelamo approved these changes

2022-09-20 05:44 UTC, merged