Kotlin version of JAX-RS guide
micronaut-projects/micronaut-guides pull request #1225
Opened 2023-01-13 16:05 UTC by sdelamo

Close #1221

2023-01-13 17:11 UTC, sdelamo commented
failure is unrelated to this guide but `spring-boot-micronaut-data`

2023-01-17 08:41 UTC, sdelamo commented
ping @timyates

2023-01-17 11:42 UTC, timyates requested changes

2023-01-17 11:42 UTC, timyates commented on cli/src/test/groovy/PetResourceTest.kt
> +import io.micronaut.core.type.Argument
I assume this is in the wrong place?

2023-01-17 17:32 UTC, timyates approved these changes

2023-01-17 18:03 UTC, merged