Paginated List | Building a rest api spring data vs micronaut data
micronaut-projects/micronaut-guides pull request #1458
Opened 2024-05-02 09:18 UTC by sdelamo

To build the guide locally:

```
./gradlew buildingARestApiSpringBootVsMicronautGetListBuild
```

2024-05-02 10:03 UTC, timyates requested changes

2024-05-02 10:03 UTC, timyates commented on guides/building-a-rest-api-spring-boot-vs-micronaut-get-list/springboot/java/src/main/java/example/micronaut/SaasSubscriptionRepository.java
> +        PagingAndSortingRepository<SaasSubscription, Long> { // <2>
We don't document (1) and (2) in the guide

2024-05-02 12:10 UTC, sdelamo commented on guides/building-a-rest-api-spring-boot-vs-micronaut-get-list/springboot/java/src/main/java/example/micronaut/SaasSubscriptionRepository.java
> +        PagingAndSortingRepository<SaasSubscription, Long> { // <2>
good catch https://github.com/micronaut-projects/micronaut-guides/pull/1458/commits/954fa5d43771bc89cbc5ba2fdb151fa3d9c38fd2

2024-05-02 12:16 UTC, timyates approved these changes

2024-05-23 10:30 UTC, graemerocher approved these changes

2024-06-18 12:32 UTC, merged