Moves getFeatures, getInvisibleFeatures, getVisibleFeatures to core. …
micronaut-projects/micronaut-guides pull request #1510
Opened 2024-10-14 10:22 UTC by AndreaLaGrotteria

…Fixes #1504

2024-10-14 11:07 UTC, sdelamo requested changes
`metadata.json` does not have invisible features, java features etc, You are basically not testing a lot of code paths.

2024-10-14 11:07 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +            addAllSafe(result,app.invisibleFeatures());
why are you calling `addAllSafe`, you know `result` is not null? You instantiated it in the previous line.

2024-10-14 11:09 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +            return mergeLists(app.features(),app.groovyFeatures());
this is not tested

2024-10-14 11:09 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +            return mergeLists(app.features(),app.kotlinFeatures());
this is not tested

2024-10-14 11:09 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +        return app.features();
this is not tested

2024-10-14 11:09 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +            return mergeLists(app.features(), getAppInvisibleFeatures(app), app.kotlinFeatures());
this is not tested

2024-10-14 11:09 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +            return mergeLists(app.features(), getAppInvisibleFeatures(app), app.groovyFeatures());
this is not tested

2024-10-14 11:09 UTC, sdelamo commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +        return mergeLists(app.features(), getAppInvisibleFeatures(app));
this is not tested

2024-10-14 12:49 UTC, AndreaLaGrotteria commented on buildSrc/src/main/java/io/micronaut/guides/core/GuideUtils.java
> +            addAllSafe(result,app.invisibleFeatures());
Because `app.invisibleFeatures()` could be null. In fact, as you can see from the implementation, `addAllSafe` is for when the 2nd argument (`src`) is null. If `target` is null it throws a NullPointerException

2024-10-15 08:53 UTC, sdelamo approved these changes

2024-10-15 08:53 UTC, merged