Adds kotlin-ext-fns guide and sample code
micronaut-projects/micronaut-guides pull request #160
Opened 2021-03-19 20:02 UTC by willbuck

Open to feedback on this one, first guide I've written in awhile!

Note that the link to the dokka docs is broken but I am working on fixing that in the kotlin repo:

https://github.com/micronaut-projects/micronaut-kotlin/issues/78

2021-03-22 11:33 UTC, ilopmar requested changes
Looks good, I've only added some minor things.

One question @willbuck, did you try it with GraalVM? I'm asking because I'm not sure if `DadJoke` needs to be annotated with `@Introspected` or not. In a Java app we put the annotation but I'm not sure in a Kotlin data class.

2021-03-22 11:33 UTC, ilopmar commented on guides/micronaut-kotlin-extension-fns/kotlin/src/test/kotlin/example/micronaut/DadJokeTest.kt
> +        val client = embeddedServer.applicationContext.createBean<HttpClient>(embeddedServer.url).toBlocking() // <2>
As you are using `@MicronautTest` you don't need to start the embedded server or create the httpclient bean. Those are available in the test and you can just `@Inject` them.
As you want to show the usage of extension functions you should remove `@MicronautTest`

2021-03-22 11:33 UTC, ilopmar commented on guides/micronaut-kotlin-extension-fns/kotlin/src/test/kotlin/example/micronaut/DadJokeTest.kt
> +        embeddedServer.close()
Same here, this is only necessary when not using `@MicronautTest`

2021-03-22 11:33 UTC, ilopmar commented on guides/micronaut-kotlin-extension-fns/micronaut-kotlin-extension-fns.adoc
> +:exclude-for-languages:
You can probably remove `:exclude-for-languages:groovy` and `:exclude-for-languages:` because this is a Kotlin-only guide.

2021-03-22 11:33 UTC, ilopmar commented on guides/micronaut-kotlin-extension-fns/outline.md
> +1. Describe kotlin extension functions
Remove this file.

2021-03-22 16:38 UTC, jeffbrown commented on guides/micronaut-kotlin-extension-fns/micronaut-kotlin-extension-fns.adoc
> +Note that while *we* are creating this client for the purposes of this guide, but often times something like this may come from
The combination of `while` and `but` reads a little awkward.  Is it better if we delete 1 of those 2 words, or leave it as it is?

2021-03-23 10:00 UTC, ilopmar approved these changes

2021-04-07 09:59 UTC, merged