Initial migration of Micronaut Data MyBatis guide
micronaut-projects/micronaut-guides pull request #176
Opened 2021-04-07 01:21 UTC by ZacharyKlein

2021-04-07 08:19 UTC, ilopmar requested changes
Besides the comments in the specific parts of the guide, you also need to:
- Remove [these lines](https://github.com/micronaut-projects/micronaut-guides-poc/blob/master/guides/micronaut-data-access-mybatis/metadata.json#L8-L9) to run the tests
- Create a `MyBatis` feature in https://github.com/micronaut-projects/micronaut-guides-poc/tree/master/buildSrc/src/main/java/io/micronaut/guides/feature and use it in https://github.com/micronaut-projects/micronaut-guides-poc/blob/master/guides/micronaut-data-access-mybatis/metadata.json#L13

Once you have it, build the guide again and make sure you run the generated `test.sh` script for the guide and all test pass.

2021-04-07 08:19 UTC, ilopmar commented on guides/micronaut-data-access-mybatis/micronaut-data-access-mybatis.adoc
> +dependency:mybatis:3.4.6[groupId=org.mybatis,callout=1]
Please make sure you use the latest MyBatis version: https://mvnrepository.com/artifact/org.mybatis/mybatis

2021-04-07 08:19 UTC, ilopmar commented on guides/micronaut-data-access-mybatis/micronaut-data-access-mybatis.adoc
> +resource:databasemigrations/V1__schema.sql[]
Please, change this and the app code to use the default location for the migrations. We changed it sometime ago in Flyway integration so it's good to have this guide aligned. See https://micronaut-projects.github.io/micronaut-flyway/latest/guide/#jpa

2021-04-07 08:19 UTC, ilopmar commented on guides/micronaut-data-access-mybatis/micronaut-data-access-mybatis.adoc
> +----
This needs to be build tool agnostic. You can do something like:

```
Run the tests:

:exclude-for-build:maven

[source, bash]
----
$ ./gradlew test
----

:exclude-for-build:

:exclude-for-build:gradle

[source, bash]
----
$ ./mvnw test
----

:exclude-for-build:
```

2021-04-07 08:19 UTC, ilopmar commented on guides/micronaut-data-access-mybatis/micronaut-data-access-mybatis.adoc
> +
Add here the section for GraalVM (change the texts if you want):

```
include::{commondir}/common-graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You can execute the same curl request as before to check that the native image works.

:exclude-for-languages:
```

2021-04-09 22:38 UTC, ZacharyKlein commented
@ilopmar I believe I was able to resolve the last test failure (there was a change in MyBatis 3.5.x that required a tweak to the annotations for generated keys). This is ready for review again.

2021-04-12 08:30 UTC, ilopmar approved these changes
Excellent!

If just pushed a minor fix to make the guide build-tool agnostic and also to remove the lookup for a specific MyBatis version. It is pulled automatically from the version in pom.xml (that is update by dependabot).

2021-04-12 10:04 UTC, merged