add reactor feature to micronaut-microservices-services-discover-consul guide
micronaut-projects/micronaut-guides pull request #481
Opened 2021-08-25 06:44 UTC by burtbeckwith

2021-09-01 13:04 UTC, sdelamo requested changes
A couple of minor comments.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookcatalogue/groovy/src/main/groovy/example/micronaut/Book.groovy
> +    @Creator
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookcatalogue/groovy/src/main/groovy/example/micronaut/BooksController.groovy
> +        Book buildingMicroservices = new Book("1491950358", "Building Microservices")
syntax without local variables is nicer

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookcatalogue/java/src/main/java/example/micronaut/Book.java
> +    @Creator
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookcatalogue/kotlin/src/main/kotlin/example/micronaut/Book.kt
> +data class Book @Creator constructor(
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookcatalogue/kotlin/src/main/kotlin/example/micronaut/BooksController.kt
> +        val buildingMicroservices = Book("1491950358", "Building Microservices")
syntax without local variables is nicer

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookinventory/groovy/src/main/groovy/example/micronaut/BookInventory.groovy
> +    @Creator
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookinventory/java/src/main/java/example/micronaut/BookInventory.java
> +    @Creator
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookinventory/kotlin/src/main/kotlin/example/micronaut/BookInventory.kt
> +data class BookInventory @Creator constructor(
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/groovy/src/main/groovy/example/micronaut/Book.groovy
> +    @Creator
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/groovy/src/main/groovy/example/micronaut/BookRecommendation.groovy
> +    @Creator
Is `@Creator` necessary? If we want to keep it, add a callout.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/groovy/src/test/groovy/example/micronaut/BookControllerSpec.groovy
> +    StreamingHttpClient client
Why did you change from `HttpClient` to `StreamingHttpClient` It seems easier to use `HttpClient::toBlocking` than using StreamingHttpClient and having to wrap it in a Flux

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/java/src/main/java/example/micronaut/Book.java
> +    @Creator
Is `@Creator` necessary? If you want to keep, we need to add a callout and explain it to the user.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/java/src/main/java/example/micronaut/BookRecommendation.java
> +    @Creator
Is `@Creator` necessary? If you want to keep, we need to add a callout and explain it to the user.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/kotlin/src/main/kotlin/example/micronaut/Book.kt
> +data class Book @Creator constructor(
Is `@Creator` necessary? If you want to keep, we need to add a callout and explain it to the user.

2021-09-01 13:04 UTC, sdelamo commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/kotlin/src/main/kotlin/example/micronaut/BookRecommendation.kt
> +data class BookRecommendation @Creator constructor(@NotBlank val name: String)
Is `@Creator` necessary? If you want to keep, we need to add a callout and explain it to the user.

2021-09-01 14:09 UTC, burtbeckwith commented on guides/micronaut-microservices-services-discover-consul/bookrecommendation/groovy/src/test/groovy/example/micronaut/BookControllerSpec.groovy
> +    StreamingHttpClient client
For all of these PRs I followed the guide for Java and made various changes there, then converted the Java to Groovy and Kotlin and merged in the changes to the existing Java and Groovy. In this case the Groovy test was inconsistent so I changed to use StreamingHttpClient like the other two

2021-09-02 11:12 UTC, sdelamo approved these changes

2021-09-02 11:12 UTC, merged