Micronaut Google Cloud HTTP Function
micronaut-projects/micronaut-guides pull request #572
Opened 2021-10-12 06:04 UTC by sdelamo

2021-10-13 08:10 UTC, ilopmar requested changes

2021-10-13 08:10 UTC, ilopmar commented on guides/micronaut-google-cloud-http-function/micronaut-google-cloud-http-function.adoc
> +----
As this is a function, why don't use `mn create-function-app` instead?

2021-10-13 08:10 UTC, ilopmar commented on guides/micronaut-google-cloud-http-function/micronaut-google-cloud-http-function.adoc
> +
Google Cloud Function only works with JDK 11. We should add a message about it. There are a few examples in the Oracle Cloud guides.

2021-10-13 08:10 UTC, ilopmar commented on guides/micronaut-google-cloud-http-function/metadata.json
> +  "publicationDate": "2021-10-01",
Add `"minimumJavaVersion": 11,` so the application is not generated for JDK 8 (as this only works with 11+)

2021-10-13 08:39 UTC, sdelamo commented on guides/micronaut-google-cloud-http-function/micronaut-google-cloud-http-function.adoc
> +----
because for functions which use controllers you create them with `create-app` not with `create-function-app`.

2021-10-14 08:55 UTC, sdelamo commented on guides/micronaut-google-cloud-http-function/metadata.json
> +  "publicationDate": "2021-10-01",
done

2021-10-14 08:56 UTC, sdelamo commented on guides/micronaut-google-cloud-http-function/micronaut-google-cloud-http-function.adoc
> +
I have created a `common-requirements-jdk11.adoc` for guides which require JDK 11

2021-10-14 09:02 UTC, ilopmar commented
Umm.... the build for JDK 8 has failed again :pensive:

2021-10-15 10:20 UTC, sdelamo commented
@kroegerk can you proofread this guide?

2021-10-15 10:21 UTC, ilopmar approved these changes

2021-10-19 09:33 UTC, merged