Keycloak
micronaut-projects/micronaut-guides pull request #586
Opened 2021-10-19 10:58 UTC by sdelamo

To generate the guide locally: `./gradlew micronautOauth2KeycloakBuild`

Sample applications are generated at build/code

HTML is generated at:

`open build/dist/micronaut-oauth2-keycloak.html`

2021-10-19 10:59 UTC, sdelamo commented
@morki Please provide PRs against  `keycloak` branch as base.

2022-06-22 14:59 UTC, sdelamo commented
Implement this guide use https://www.keycloak.org 18.0 

See: https://github.com/micronaut-projects/micronaut-security/issues/1024

2022-06-22 20:52 UTC, morki commented
Oh, sorry @sdelamo, I totally forget about this one.

2023-04-13 13:24 UTC, sdelamo commented
@morki this is ready in case you want to review.

2023-04-13 13:49 UTC, wetted requested changes

2023-04-13 13:49 UTC, wetted commented on guides/micronaut-oauth2-keycloak/micronaut-oauth2-keycloak.adoc
> +callout:authentication-idtoken[number=1,arg0=Keycloack]
```suggestion
callout:authentication-idtoken[number=1,arg0=Keycloak]
```

2023-04-13 13:58 UTC, wetted approved these changes

2023-04-13 15:35 UTC, merged