flyway guide
micronaut-projects/micronaut-guides pull request #634
Opened 2021-11-21 10:04 UTC by sdelamo

2021-11-21 20:12 UTC, sdelamo commented
@kroegerk can you proofread it ?

2021-11-22 09:05 UTC, ilopmar commented on guides/micronaut-flyway/micronaut-flyway.adoc
> +export VAT_PERCENTAGE=20
Remove `export VAT_PERCENTAGE=20` because it's not used in this guide. Please also remove it in the Liquibase guide.

2021-11-22 09:06 UTC, ilopmar commented on guides/micronaut-flyway/micronaut-flyway.adoc
> +Learn more about (https://flywaydb.org)[Flyway].
Remove the parenthesis. Not needed in Asciidoctor and the output is rendered as:
![image](https://user-images.githubusercontent.com/559192/142833120-1b4ff5a6-8009-4d90-b16d-cb1ae596265b.png)

2021-11-22 09:06 UTC, ilopmar requested changes
Besides the comments, there are a couple of Asciidoctor warnings:

```

> Task :asciidoctor
Nov 22, 2021 10:00:06 AM uri:classloader:/gems/asciidoctor-2.0.12/lib/asciidoctor/parser.rb next_block
WARNING: micronaut-flyway-gradle-java.adoc: line 283: callout list item index: expected 4, got 3

> Task :cli:startShadowScripts
> Task :cli:shadowDistTar

> Task :asciidoctor
Nov 22, 2021 10:00:07 AM uri:classloader:/gems/asciidoctor-2.0.12/lib/asciidoctor/parser.rb next_block
WARNING: micronaut-flyway-maven-java.adoc: line 299: callout list item index: expected 4, got 3

> Task :copyHtmlToDist
```

2021-11-22 09:50 UTC, ilopmar approved these changes

2021-11-22 10:02 UTC, merged

2021-11-22 16:12 UTC, kroegerk commented on guides/micronaut-flyway/metadata.json
> +      "intro": "Learn how to use the Flyway to manage your schema migrations.",
remove "the" from in front of Flyway

Learn how to use Flyway to manage your schema migrations.

2021-11-22 16:14 UTC, kroegerk commented on guides/micronaut-flyway/micronaut-flyway.adoc
> +<1> Enable flyway for the `default` datasource.
Capitalize "flyway" for consistency

2021-11-22 16:14 UTC, kroegerk commented on guides/micronaut-flyway/micronaut-flyway.adoc
> +NOTE: Micronaut flyway integration works with multiple datasources.
Capitalize "flyway" for consistency

2021-11-22 16:15 UTC, kroegerk commented on guides/micronaut-flyway/micronaut-flyway.adoc
> +Create a test that invokes the Flyway endpoint
Add a period to the end of this sentence.

2021-11-22 16:16 UTC, kroegerk commented on guides/micronaut-flyway/micronaut-flyway.adoc
> +<4> You handle database migrations via Flyway
Add a period to the end of this sentence.

2021-11-22 16:17 UTC, kroegerk reviewed
Looks good. There were just a couple of tiny changes for consistency.