Groovy and Kotlin source for micronaut-token-propagation
micronaut-projects/micronaut-guides pull request #825
Opened 2022-03-05 15:23 UTC by burtbeckwith

2022-03-06 06:05 UTC, sdelamo requested changes

2022-03-06 06:05 UTC, sdelamo commented on guides/micronaut-token-propagation/gateway/groovy/src/test/groovy/example/micronaut/UserControllerSpec.groovy
> +                .header('Authorization', 'Bearer ' + bearerAccessRefreshToken.accessToken), String)
Please, use [HttpRequest.bearerAuth](https://docs.micronaut.io/2.4.2/api/io/micronaut/http/MutableHttpRequest.html#bearerAuth-java.lang.CharSequence-)

2022-03-06 06:05 UTC, sdelamo commented on guides/micronaut-token-propagation/gateway/kotlin/src/test/kotlin/example/micronaut/UserControllerTest.kt
> +                .header("Authorization", "Bearer " + bearerAccessRefreshToken.accessToken), String::class.java)
Please use [`HttpRequest::bearerAuth`](https://docs.micronaut.io/2.4.2/api/io/micronaut/http/MutableHttpRequest.html#bearerAuth-java.lang.CharSequence-)

2022-03-06 06:05 UTC, sdelamo commented on guides/micronaut-token-propagation/intermediate-gateway/groovy/src/test/groovy/example/micronaut/UserControllerSpec.groovy
> +                .header('Authorization', 'Bearer ' + bearerAccessRefreshToken.getAccessToken()), String)
Please use [`HttpRequest::bearerAuth`](https://docs.micronaut.io/2.4.2/api/io/micronaut/http/MutableHttpRequest.html#bearerAuth-java.lang.CharSequence-)

2022-03-07 03:36 UTC, sdelamo approved these changes

2022-03-07 03:36 UTC, sdelamo commented
@burtbeckwith could you check the failing tests?

2022-03-07 06:01 UTC, burtbeckwith commented
@sdelamo I manually fixed the 2 GitHub workflows for this guide, and fixed the issue in https://github.com/micronaut-projects/micronaut-guides/pull/826

2022-03-07 15:46 UTC, merged