Add command-line steps, and update some common snippets
micronaut-projects/micronaut-guides pull request #884
Opened 2022-04-08 13:47 UTC by alvarosanchez

Fixes #698

2022-04-08 13:48 UTC, alvarosanchez commented
Created as draft since there is some missing step in the user pool creation that makes signup not working

2022-04-12 08:38 UTC, sdelamo requested changes

2022-04-12 08:38 UTC, sdelamo commented on src/docs/common/snippets/common-cognito.adoc
> +Alternatively, you can use the AWS CLI to create the user pool and client (change the region to your desired value):
Add a section header. So that we can link users to the CLI section.

2022-04-12 08:46 UTC, alvarosanchez commented on src/docs/common/snippets/common-cognito.adoc
> +Alternatively, you can use the AWS CLI to create the user pool and client (change the region to your desired value):
Done

2022-04-12 08:52 UTC, sdelamo approved these changes

2022-04-12 09:22 UTC, merged