Composite Pattern
micronaut-projects/micronaut-guides pull request #902
Opened 2022-04-25 13:11 UTC by sdelamo

2022-04-25 14:04 UTC, alvarosanchez commented on guides/micronaut-patterns-composite/micronaut-patterns-composite.adoc
> +Imagine you want to create an API to resolve a color:
The guide is great. But I miss an introduction paragraph. You jump straight to the solution of a problem/need that is worth introducing first, IMO.

2022-04-25 14:06 UTC, alvarosanchez requested changes
The guide is great. But I miss an introduction paragraph. You jump straight to the solution of a problem/need that is worth introducing first, IMO.

2022-04-25 14:21 UTC, timyates approved these changes
Approve, but agree with @alvarosanchez's review

A paragraph explaining what we're trying to do, and then another at the end of the controller section explaining what we are going to do to fix it would improve it imho

https://github.com/micronaut-projects/micronaut-guides/blob/cc21564b1725f66451dec2c64e9038c9ef99635f/guides/micronaut-patterns-composite/micronaut-patterns-composite.adoc#L50-L74

2022-05-04 23:08 UTC, sdelamo commented
> The guide is great. But I miss an introduction paragraph. You jump straight to the solution of a problem/need that is worth introducing first, IMO.

I have added an introduction paragraph

https://github.com/micronaut-projects/micronaut-guides/pull/902/commits/13f4789fd4b3932818bf7edd04b73f027b439fd0

Moreover, [I have removed tests from the asciidoc to reduce clutter](https://github.com/micronaut-projects/micronaut-guides/pull/902/commits/0ffd6bc9426364e4dc0e8776e3d5b038003ddc2b)

2022-05-05 09:23 UTC, alvarosanchez approved these changes

2022-05-05 15:08 UTC, merged