OCI email delivery guide
micronaut-projects/micronaut-guides pull request #909
Opened 2022-04-27 21:13 UTC by hari09krishna

2022-04-27 21:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-guides?pullRequest=909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-guides?pullRequest=909) before we can accept your contribution.<br/><hr/>**hasivval** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-guides?pullRequest=909) it.</sub>

2022-04-28 14:06 UTC, graemerocher commented
@hari09krishna could you create the PR with the same account as you created the commits with, otherwise the CLA validation won't work

2022-05-04 12:48 UTC, shingjo commented on guides/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery.adoc
> +https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.10.4/oci_cli_docs/cmdref/iam/group/create.html[Create a group] by running:
Change the URL to `https://docs.oracle.com/en-us/iaas/tools/oci-cli/latest/oci_cli_docs/cmdref/iam/group/create.html` **latest** vs **2.10.4**.

Note: latest == 3.8.1

2022-05-04 12:48 UTC, shingjo commented on guides/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery.adoc
> +https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.10.4/oci_cli_docs/cmdref/iam/user/create.html[Create a user] by running:
Update all of these to **latest** vs **2.10.4**

2022-05-04 12:48 UTC, shingjo commented on guides/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery.adoc
> +export GRP_ID=ocid1.group.oc1..aaaaaaaaqx...
Might want to add something like:

```
[NOTE]
.Window System
====
Command Prompt:: Change '*export*' to '*set*'
+
Example: `set GRP_ID=ocid1.group.oc1..aaaaaaaaqx...

PowerShell:: Change '*export* ' to '*$*' and use quotes around the value
+
Example: `$GRP_ID="ocid1.group.oc1..aaaaaaaaqx...`
====
```
For the first occurrence of the `export` commands.

2022-05-04 12:48 UTC, shingjo commented on guides/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery.adoc
> +common:annotationprocessors.adoc[]
This can be replaced with: 
`common:create-app.adoc[]`

2022-05-04 13:51 UTC, hari09krishna commented on guides/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery.adoc
> +https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.10.4/oci_cli_docs/cmdref/iam/group/create.html[Create a group] by running:
Thanks for the comment. changes are done.

2022-05-05 15:13 UTC, hari09krishna commented on guides/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery.adoc
> +export GRP_ID=ocid1.group.oc1..aaaaaaaaqx...
Hi, I'm using the standard template used in the other guides on using commands with windows. Let me know if you still think it needs to be updated

2022-05-05 15:25 UTC, shingjo commented on guides/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery.adoc
> +export GRP_ID=ocid1.group.oc1..aaaaaaaaqx...
You are correct, missed `common:env-vars.adoc[]` since it is new-ish.

2022-05-05 15:26 UTC, shingjo approved these changes

2022-05-06 10:48 UTC, graemerocher commented
The build fails for me with:

```
Executing 'micronaut-oracle-email-delivery-maven-groovy' tests
[ERROR] COMPILATION ERROR :
[ERROR] /Users/gkrocher/dev/micronaut/guides/build/code/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery-maven-groovy/target/generated-sources/groovy-stubs/test/example/micronaut/EmailSenderReplacement.java:[9,249] cannot find symbol
  symbol: variable NAME
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project micronautguide: Compilation failure
[ERROR] /Users/gkrocher/dev/micronaut/guides/build/code/micronaut-oracle-email-delivery/micronaut-oracle-email-delivery-maven-groovy/target/generated-sources/groovy-stubs/test/example/micronaut/EmailSenderReplacement.java:[9,249] cannot find symbol
[ERROR]   symbol: variable NAME
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
'micronaut-oracle-email-delivery-maven-groovy' tests failed => exit 1
-------------------------------------------------
Executing 'micronaut-oracle-email-delivery-maven-kotlin' tests
[ERROR] Note: Creating bean classes for 2 type elements
[ERROR] Note: Creating bean classes for 3 type elements
12:47:27.515 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
12:47:28.208 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]

-------------------------------------------------
Projects with errors:
  micronaut-oracle-email-delivery-maven-groovy
-------------------------------------------------

> Task :micronautOracleEmailDeliveryRunTestScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':micronautOracleEmailDeliveryRunTestScript'.
> There was a failure while executing work items
   > A failure occurred while executing io.micronaut.guides.tasks.TestScriptRunnerWorkAction
      > Process 'command './test.sh'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 22s
22 actionable tasks: 14 executed, 8 up-to-date

A build scan was not published as you have not authenticated with server 'ge.micronaut.io'.
```

2022-05-06 11:08 UTC, graemerocher requested changes
I think testing can be simplified quite a bit with mocking.

The following diff shows how the Java code can be simplified:

```diff
diff --git a/src/test/java/example/micronaut/EmailControllerTest.java b/src/test/java/example/micronaut/EmailControllerTest.java
index 0d140b5..5300fd7 100644
--- a/src/test/java/example/micronaut/EmailControllerTest.java
+++ b/src/test/java/example/micronaut/EmailControllerTest.java
@@ -1,36 +1,38 @@
 package example.micronaut;

-import io.micronaut.context.BeanContext;
-import io.micronaut.context.annotation.Property;
+import static java.nio.charset.StandardCharsets.UTF_8;
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Optional;
+import java.util.function.Consumer;
+
+import org.junit.jupiter.api.AfterEach;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertNotNull;
+import static org.junit.jupiter.api.Assertions.assertNull;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+import org.junit.jupiter.api.Test;
+
 import io.micronaut.email.Attachment;
+import static io.micronaut.email.BodyType.HTML;
+import static io.micronaut.email.BodyType.TEXT;
 import io.micronaut.email.Email;
+import io.micronaut.email.EmailException;
 import io.micronaut.email.TransactionalEmailSender;
 import io.micronaut.http.HttpRequest;
 import io.micronaut.http.HttpResponse;
-import io.micronaut.http.client.HttpClient;
-import io.micronaut.http.client.annotation.Client;
-import io.micronaut.http.client.multipart.MultipartBody;
-import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
-import jakarta.inject.Inject;
-import org.junit.jupiter.api.BeforeEach;
-import org.junit.jupiter.api.Test;
-
-import java.util.Optional;
-
-import static io.micronaut.email.BodyType.HTML;
-import static io.micronaut.email.BodyType.TEXT;
 import static io.micronaut.http.HttpStatus.OK;
 import static io.micronaut.http.MediaType.MULTIPART_FORM_DATA_TYPE;
 import static io.micronaut.http.MediaType.TEXT_CSV;
 import static io.micronaut.http.MediaType.TEXT_CSV_TYPE;
 import static io.micronaut.http.MediaType.TEXT_PLAIN_TYPE;
-import static java.nio.charset.StandardCharsets.UTF_8;
-import static org.junit.jupiter.api.Assertions.assertEquals;
-import static org.junit.jupiter.api.Assertions.assertNotNull;
-import static org.junit.jupiter.api.Assertions.assertNull;
-import static org.junit.jupiter.api.Assertions.assertTrue;
+import io.micronaut.http.client.HttpClient;
+import io.micronaut.http.client.annotation.Client;
+import io.micronaut.http.client.multipart.MultipartBody;
+import io.micronaut.test.annotation.MockBean;
+import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
+import jakarta.inject.Inject;

-@Property(name = "spec.name", value = "EmailControllerTest") // <1>
 @MicronautTest // <2>
 class EmailControllerTest {

@@ -38,19 +40,13 @@ class EmailControllerTest {
     @Client("/")
     HttpClient client; // <3>

-    @Inject
-    BeanContext beanContext;
+    List<Email> emails = new ArrayList<>();

-    private EmailSenderReplacement sender;
-
-    @BeforeEach
-    void setup() {
-        TransactionalEmailSender<?, ?> sender = beanContext.getBean(TransactionalEmailSender.class);
-        assertTrue(sender instanceof EmailSenderReplacement);
-        this.sender = (EmailSenderReplacement) sender;
-        this.sender.getEmails().clear();
+    @AfterEach
+    void cleanup() {
+        emails.clear();
     }
-
+
     @Test
     void testBasic() {

@@ -58,8 +54,8 @@ class EmailControllerTest {
                 HttpRequest.POST("/email/basic", null));
         assertEquals(response.status(), OK);

-        assertEquals(1, sender.emails.size());
-        Email email = sender.getEmails().get(0);
+        assertEquals(1, emails.size());
+        Email email = emails.get(0);

         assertEquals("test@test.com", email.getFrom().getEmail());

@@ -90,8 +86,8 @@ class EmailControllerTest {
                 HttpRequest.POST("/email/template/testingtesting", null));
         assertEquals(response.status(), OK);

-        assertEquals(1, sender.emails.size());
-        Email email = sender.getEmails().get(0);
+        assertEquals(1, emails.size());
+        Email email = emails.get(0);

         assertEquals("test@test.com", email.getFrom().getEmail());

@@ -127,8 +123,8 @@ class EmailControllerTest {
                 String.class);
         assertEquals(response.status(), OK);

-        assertEquals(1, sender.emails.size());
-        Email email = sender.getEmails().get(0);
+        assertEquals(1, emails.size());
+        Email email = emails.get(0);

         assertEquals("test@test.com", email.getFrom().getEmail());

@@ -156,4 +152,20 @@ class EmailControllerTest {
         Optional<String> body = email.getBody().get(TEXT);
         assertEquals("Attachment email", body.orElseThrow());
     }
+
+    @MockBean(TransactionalEmailSender.class)
+    TransactionalEmailSender mockSender() {
+        return new TransactionalEmailSender() {
+            @Override
+            public String getName() {
+                return "test";
+            }
+
+            @Override
+            public Object send(Email email, Consumer emailRequest) throws EmailException {
+                emails.add(email);
+                return email;
+            }
+        };
+    }
 }
diff --git a/src/test/java/example/micronaut/EmailSenderReplacement.java b/src/test/java/example/micronaut/EmailSenderReplacement.java
deleted file mode 100644
index e318583..0000000
--- a/src/test/java/example/micronaut/EmailSenderReplacement.java
+++ /dev/null
@@ -1,43 +0,0 @@
-package example.micronaut;
-
-import io.micronaut.context.annotation.Replaces;
-import io.micronaut.context.annotation.Requires;
-import io.micronaut.email.Email;
-import io.micronaut.email.EmailException;
-import io.micronaut.email.TransactionalEmailSender;
-import jakarta.inject.Named;
-import jakarta.inject.Singleton;
-
-import javax.mail.Message;
-import javax.validation.Valid;
-import javax.validation.constraints.NotNull;
-import java.util.ArrayList;
-import java.util.List;
-import java.util.function.Consumer;
-
-@Requires(property = "spec.name", value = "EmailControllerTest") // <1>
-@Singleton
-@Replaces(TransactionalEmailSender.class)
-@Named(EmailSenderReplacement.NAME)
diff --git a/src/test/java/example/micronaut/EmailControllerTest.java b/src/test/java/example/micronaut/EmailControllerTest.java
index 0d140b5..5300fd7 100644
--- a/src/test/java/example/micronaut/EmailControllerTest.java
+++ b/src/test/java/example/micronaut/EmailControllerTest.java
@@ -1,36 +1,38 @@
 package example.micronaut;

-import io.micronaut.context.BeanContext;
-import io.micronaut.context.annotation.Property;
+import static java.nio.charset.StandardCharsets.UTF_8;
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Optional;
+import java.util.function.Consumer;
+
+import org.junit.jupiter.api.AfterEach;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertNotNull;
+import static org.junit.jupiter.api.Assertions.assertNull;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+import org.junit.jupiter.api.Test;
+
 import io.micronaut.email.Attachment;
+import static io.micronaut.email.BodyType.HTML;
+import static io.micronaut.email.BodyType.TEXT;
 import io.micronaut.email.Email;
+import io.micronaut.email.EmailException;
 import io.micronaut.email.TransactionalEmailSender;
 import io.micronaut.http.HttpRequest;
 import io.micronaut.http.HttpResponse;
-import io.micronaut.http.client.HttpClient;
-import io.micronaut.http.client.annotation.Client;
-import io.micronaut.http.client.multipart.MultipartBody;
-import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
-import jakarta.inject.Inject;
-import org.junit.jupiter.api.BeforeEach;
-import org.junit.jupiter.api.Test;
-
-import java.util.Optional;
-
-import static io.micronaut.ema [...]

2022-05-06 11:08 UTC, graemerocher commented on guides/micronaut-oracle-email-delivery/java/src/main/java/example/micronaut/EmailController.java
> +class EmailController {
add `@ExecuteOn(TaskExecutors.IO)` since you are using blocking logic

2022-05-06 11:09 UTC, graemerocher commented
Simplified test code:

```java
package example.micronaut;

import static java.nio.charset.StandardCharsets.UTF_8;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;

import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

import io.micronaut.email.Attachment;
import static io.micronaut.email.BodyType.HTML;
import static io.micronaut.email.BodyType.TEXT;
import io.micronaut.email.Email;
import io.micronaut.email.EmailException;
import io.micronaut.email.TransactionalEmailSender;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpResponse;
import static io.micronaut.http.HttpStatus.OK;
import static io.micronaut.http.MediaType.MULTIPART_FORM_DATA_TYPE;
import static io.micronaut.http.MediaType.TEXT_CSV;
import static io.micronaut.http.MediaType.TEXT_CSV_TYPE;
import static io.micronaut.http.MediaType.TEXT_PLAIN_TYPE;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.http.client.multipart.MultipartBody;
import io.micronaut.test.annotation.MockBean;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import jakarta.inject.Named;

@MicronautTest // <2>
class EmailControllerTest {

    @Inject
    @Client("/")
    HttpClient client; // <3>

    List<Email> emails = new ArrayList<>();

    @AfterEach
    void cleanup() {
        emails.clear();
    }
    
    @Test
    void testBasic() {

        HttpResponse<?> response = client.toBlocking().exchange(
                HttpRequest.POST("/email/basic", null));
        assertEquals(response.status(), OK);

        assertEquals(1, emails.size());
        Email email = emails.get(0);

        assertEquals("test@test.com", email.getFrom().getEmail());

        assertNull(email.getReplyTo());

        assertNotNull(email.getTo());
        assertEquals(1, email.getTo().size());
        assertEquals("basic@domain.com", email.getTo().iterator().next().getEmail());
        assertNull(email.getTo().iterator().next().getName());

        assertNull(email.getCc());

        assertNull(email.getBcc());

        assertTrue(email.getSubject().startsWith("Micronaut Email Basic Test: "));

        assertNull(email.getAttachments());

        assertNotNull(email.getBody());
        Optional<String> body = email.getBody().get(TEXT);
        assertEquals("Basic email", body.orElseThrow());
    }

    @Test
    void testTemplate() {

        HttpResponse<?> response = client.toBlocking().exchange(
                HttpRequest.POST("/email/template/testingtesting", null));
        assertEquals(response.status(), OK);

        assertEquals(1, emails.size());
        Email email = emails.get(0);

        assertEquals("test@test.com", email.getFrom().getEmail());

        assertNull(email.getReplyTo());

        assertNotNull(email.getTo());
        assertEquals(1, email.getTo().size());
        assertEquals("template@domain.com", email.getTo().iterator().next().getEmail());
        assertNull(email.getTo().iterator().next().getName());

        assertNull(email.getCc());

        assertNull(email.getBcc());

        assertTrue(email.getSubject().startsWith("Micronaut Email Template Test: "));

        assertNull(email.getAttachments());

        assertNotNull(email.getBody());
        Optional<String> body = email.getBody().get(HTML);
        assertTrue(body.orElseThrow().contains("Hello, <span>testingtesting</span>!"));
    }

    @Test
    void testAttachment() {

        HttpResponse<?> response = client.toBlocking().exchange(
                HttpRequest.POST("/email/attachment", MultipartBody.builder()
                        .addPart("file", "test.csv", TEXT_CSV_TYPE, "test,email".getBytes(UTF_8))
                        .build())
                        .contentType(MULTIPART_FORM_DATA_TYPE)
                        .accept(TEXT_PLAIN_TYPE),
                String.class);
        assertEquals(response.status(), OK);

        assertEquals(1, emails.size());
        Email email = emails.get(0);

        assertEquals("test@test.com", email.getFrom().getEmail());

        assertNull(email.getReplyTo());

        assertNotNull(email.getTo());
        assertEquals(1, email.getTo().size());
        assertEquals("attachment@domain.com", email.getTo().iterator().next().getEmail());
        assertNull(email.getTo().iterator().next().getName());

        assertNull(email.getCc());

        assertNull(email.getBcc());

        assertTrue(email.getSubject().startsWith("Micronaut Email Attachment Test: "));

        assertNotNull(email.getAttachments());
        assertEquals(1, email.getAttachments().size());
        Attachment attachment = email.getAttachments().get(0);
        assertEquals("test.csv", attachment.getFilename());
        assertEquals(TEXT_CSV, attachment.getContentType());
        assertEquals("test,email", new String(attachment.getContent()));

        assertNotNull(email.getBody());
        Optional<String> body = email.getBody().get(TEXT);
        assertEquals("Attachment email", body.orElseThrow());
    }

    @MockBean(TransactionalEmailSender.class)
    @Named("mock")
    TransactionalEmailSender mockSender() {
        return new TransactionalEmailSender() {
            @Override
            public String getName() {
                return "test";
            }            

            @Override
            public Object send(Email email, Consumer emailRequest) throws EmailException {
                emails.add(email);
                return email;
            }
        };
    }
}
```

2022-05-12 15:44 UTC, shingjo approved these changes

2022-05-13 10:50 UTC, graemerocher approved these changes

2022-05-13 15:06 UTC, alvarosanchez approved these changes

2022-05-17 11:08 UTC, sdelamo commented
Great guide, I have merged it here: https://github.com/micronaut-projects/micronaut-guides/pull/932

Thanks for writing it @hari09krishna

2022-05-17 11:08 UTC, closed without merging