Xrayguide opentelemetry
micronaut-projects/micronaut-guides pull request #976
Opened 2022-06-14 13:57 UTC by sdelamo

Steps to build the locally: 

````
./gradlew micronautMicroservicesDistributedTracingXrayBuild -x micronautMicroservicesDistributedTracingXrayRunTestScript
```

replace 

in build.gradle replace: 

```
depednencies {
```
with: 
```
    mavenLocal()
}

dependencies {
    annotationProcessor(platform("io.micronaut.tracing:micronaut-tracing-bom:4.2.0-SNAPSHOT"))
    implementation(platform("io.micronaut.tracing:micronaut-tracing-bom:4.2.0-SNAPSHOT"))
```

Clone  `https://github.com/aws-observability/aws-otel-collector`

Edit `examples/docker/config-test.yaml` and use `us-east-1`

and run the Aws OpenTelementry Collector
```
docker run --rm -p 4317:4317 -p 55680:55680 -p 8889:8888 -e AWS_REGION=us-east-1 -e AWS_PROFILE=default -v ~/.aws:/root/.aws -v "${PWD}/examples/docker/config-test.yaml":/otel-local-config.yaml --name awscollector public.ecr.aws/aws-observability/aws-otel-collector:latest --config otel-local-config.yaml
```

2022-07-04 12:16 UTC, timyates requested changes
This is missing the part about setting up

```
dynamodb-local:
  host: localhost
  port: 8000
```

In `application-dev.yml` for bookinventory and bookcatalogue

And also it needs [`src/docs/common/snippets/common-run-dynamodb-with-docker.adoc`](https://github.com/micronaut-projects/micronaut-guides/pull/996/files#diff-43144f350447b277b18bc1101d3a3b9bc7e9c7f566db1ec95ee3fa6c61559984) from, the dynamodb guide PR injected into to asciidoc (as without a local running dynamodb, `./gradlew run` fails)

2022-07-04 12:20 UTC, timyates commented
Updated the issue description now xray support is out in tracing:4.2.0

2022-07-06 14:29 UTC, shingjo approved these changes

2022-07-06 14:29 UTC, shingjo commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +=== OpenTelemetry annotations
There isn't any OT annotations.

2022-07-11 11:09 UTC, sdelamo commented
The classes under `buildSrc` will be removed once 3.6.0 is out

2022-07-11 11:09 UTC, sdelamo commented
@kroegerk can you proofread it?

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/metadata.json
> +  "title": "Microservices distributed tracing with XRay and Micronaut Framework",
```suggestion
  "title": "Microservices Distributed Tracing with X-Ray and the Micronaut Framework",
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/metadata.json
> +  "intro": "Use XRay distributed tracing to investigate the behaviour of your Micronaut applications.",
```suggestion
  "intro": "Use AWS X-Ray distributed tracing to investigate the behavior of your Micronaut applications.",
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +AWS X-Ray helps developers analyze and debug production, distributed applications, such as those built using a microservices architecture. With X-Ray, you can understand how your application and its
```suggestion
AWS X-Ray helps developers analyze and debug distributed applications, such as those built using a microservices architecture. With X-Ray, you can understand how your application and its underlying services are performing to identify and troubleshoot the root cause of performance issues and errors. X-Ray provides an end-to-end view of requests as they travel through your application and displays a map of your application’s underlying components. You can use X-Ray to analyze both applications in development and in production, from simple three-tier applications to complex microservices applications consisting of thousands of services.
```

I know you copied this directly from the AWS site, but the first sentence doesn't make sense as written and the comma I removed does not belong there. :-)

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +* `bookcatalogue` - It returns a list of books. It uses a domain consisting of a book name and ISBN.
```suggestion
* `bookcatalogue` - Returns a list of books. It uses a domain consisting of a book name and an ISBN.
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +* `bookinventory` - It exposes an endpoint to check whether a book has sufficient stock to fulfill an order. It uses a domain consisting of a stock level and ISBN.
```suggestion
* `bookinventory` - Exposes an endpoint to check whether a book has sufficient stock to fulfill an order. It uses a domain consisting of a stock level and an ISBN.
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +* `bookrecommendation` - It consumes previous services and exposes an endpoint recommending book names in stock.
```suggestion
* `bookrecommendation` - Consumes previous services and exposes an endpoint recommending book names in stock.
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +To enable creating span objects on the every HTTP server request, client request, server response and client response
```suggestion
To enable creation of span objects on every HTTP server request, client request, server response, and client response,
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +To use AWS X-Ray propagator each service adds the following dependency:
```suggestion
To use AWS X-Ray propagator, each service adds the following dependency:
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +They allow you to enable https://aws-otel.github.io/docs/getting-started/java-sdk/trace-manual-instr#using-the-aws-resource-detectors[AWS resource detectors for enriching traces
It's not clear here what "they" refers to.

```suggestion
These dependencies allow you to enable https://aws-otel.github.io/docs/getting-started/java-sdk/trace-manual-instr#using-the-aws-resource-detectors[AWS resource detectors for enriching traces
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +Micronaut OpenTelemetry registers a tracing interceptor by creating a bean creation listener for the bean of type `SdkClientBuilder`.
```suggestion
Micronaut OpenTelemetry registers a tracing interceptor by creating a bean-creation listener for the bean of type `SdkClientBuilder`.
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +You can then navigate to AWS Console and access the X-Ray UI
```suggestion
You can then navigate to AWS Console and access the X-Ray UI.
```

2022-07-11 23:07 UTC, kroegerk commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +As you have seen in this guide, you get distributing tracing up-and-running fast with the Micronaut framework without any annotations.
```suggestion
As you have seen in this guide, you get distributed tracing up and running fast with the Micronaut framework without any annotations.
```

2022-07-12 09:40 UTC, timyates commented on guides/micronaut-microservices-distributed-tracing-xray/micronaut-microservices-distributed-tracing-xray.adoc
> +=== OpenTelemetry annotations
Removed 👍

2022-08-04 07:42 UTC, merged